[package]
name = "lesson18-hw3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rand = { version = "0.9" }
tokio = { version = "1.50", features = ["full"] }
wincode = {version = "0.4" , features =["std", "derive"]}
# thiserror = { version = ""}
anyhow = "1.0"
log = "0.4"
ftail = "0.3"

[lib]
name = "common"         # The name of the target.
path = "src/lib/lib.rs"
